version: "2"
run:
  go: "1.24"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
